# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGridLayout, QGroupBox,
    QHBoxLayout, QLabel, QLineEdit, QMainWindow,
    QMenuBar, QPlainTextEdit, QPushButton, QSizePolicy,
    QStatusBar, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.WindowModality.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(700, 516)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(700, 516))
        MainWindow.setMaximumSize(QSize(100000, 100000))
        MainWindow.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        MainWindow.setStyleSheet(u"background-color: rgb(80, 0, 0);\n"
"color: rgb(255, 255, 255);")
        MainWindow.setAnimated(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy1)
        self.centralwidget.setMinimumSize(QSize(700, 500))
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy1)
        self.frame.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.frame.setFrameShape(QFrame.Shape.Box)
        self.frame.setFrameShadow(QFrame.Shadow.Plain)
        self.frame.setLineWidth(1)
        self.verticalLayout = QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.groupBox_2 = QGroupBox(self.frame)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setEnabled(True)
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy2)
        self.groupBox_2.setMinimumSize(QSize(0, 60))
        self.groupBox_2.setMaximumSize(QSize(16777215, 60))
        font = QFont()
        font.setBold(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.groupBox_2.setStyleSheet(u"background-color: rgb(48, 0, 0);")
        self.horizontalLayout_3 = QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.runButton = QPushButton(self.groupBox_2)
        self.runButton.setObjectName(u"runButton")
        self.runButton.setEnabled(True)
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.runButton.sizePolicy().hasHeightForWidth())
        self.runButton.setSizePolicy(sizePolicy3)
        self.runButton.setFont(font)
        self.runButton.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.runButton.setStyleSheet(u"background-color: rgb(85, 0, 0);\n"
"")

        self.horizontalLayout_3.addWidget(self.runButton)

        self.stopButton = QPushButton(self.groupBox_2)
        self.stopButton.setObjectName(u"stopButton")
        self.stopButton.setEnabled(True)
        sizePolicy3.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy3)
        self.stopButton.setFont(font)
        self.stopButton.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.stopButton.setStyleSheet(u"background-color: rgb(85, 0, 0);")

        self.horizontalLayout_3.addWidget(self.stopButton)

        self.runtimeLabel = QLabel(self.groupBox_2)
        self.runtimeLabel.setObjectName(u"runtimeLabel")
        self.runtimeLabel.setEnabled(True)
        self.runtimeLabel.setFont(font)
        self.runtimeLabel.setFocusPolicy(Qt.FocusPolicy.ClickFocus)

        self.horizontalLayout_3.addWidget(self.runtimeLabel)

        self.label_7 = QLabel(self.groupBox_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setEnabled(True)
        self.label_7.setFont(font)
        self.label_7.setFocusPolicy(Qt.FocusPolicy.ClickFocus)

        self.horizontalLayout_3.addWidget(self.label_7)

        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 100)
        self.horizontalLayout_3.setStretch(3, 1)

        self.verticalLayout.addWidget(self.groupBox_2)

        self.frame_2 = QFrame(self.frame)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setEnabled(True)
        self.frame_2.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.frame_2.setFrameShape(QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.frame_4 = QFrame(self.frame_2)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setEnabled(True)
        self.frame_4.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.frame_4.setFrameShape(QFrame.Shape.NoFrame)
        self.frame_4.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout = QHBoxLayout(self.frame_4)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.frame_7 = QFrame(self.frame_4)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setEnabled(True)
        self.frame_7.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.frame_7.setFrameShape(QFrame.Shape.NoFrame)
        self.frame_7.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.frame_7)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.groupBox_3 = QGroupBox(self.frame_7)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.groupBox_3.setStyleSheet(u"background-color: rgb(48, 0, 0);")
        self.groupBox_3.setFlat(False)
        self.gridLayout_2 = QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(20, 20, 20, 20)
        self.label_2 = QLabel(self.groupBox_3)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setEnabled(True)
        font1 = QFont()
        font1.setBold(True)
        font1.setKerning(True)
        self.label_2.setFont(font1)
        self.label_2.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)

        self.label = QLabel(self.groupBox_3)
        self.label.setObjectName(u"label")
        self.label.setEnabled(True)
        self.label.setFont(font1)
        self.label.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)

        self.label_3 = QLabel(self.groupBox_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setEnabled(True)
        self.label_3.setFont(font1)
        self.label_3.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_2.addWidget(self.label_3, 0, 2, 1, 1)

        self.label_4 = QLabel(self.groupBox_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setEnabled(True)
        self.label_4.setFont(font1)
        self.label_4.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)

        self.rpmLabel = QLabel(self.groupBox_3)
        self.rpmLabel.setObjectName(u"rpmLabel")
        self.rpmLabel.setEnabled(True)
        self.rpmLabel.setFont(font1)
        self.rpmLabel.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.rpmLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_2.addWidget(self.rpmLabel, 1, 2, 1, 1)

        self.rpmEdit = QLineEdit(self.groupBox_3)
        self.rpmEdit.setObjectName(u"rpmEdit")
        self.rpmEdit.setEnabled(True)
        self.rpmEdit.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.rpmEdit.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.rpmEdit.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly)
        self.rpmEdit.setReadOnly(False)

        self.gridLayout_2.addWidget(self.rpmEdit, 1, 1, 1, 1)

        self.gridLayout_2.setRowStretch(0, 1)
        self.gridLayout_2.setRowStretch(1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setColumnStretch(2, 1)

        self.verticalLayout_3.addWidget(self.groupBox_3)

        self.groupBox = QGroupBox(self.frame_7)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setEnabled(True)
        sizePolicy3.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy3)
        self.groupBox.setFont(font)
        self.groupBox.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.groupBox.setStyleSheet(u"background-color: rgb(48, 0, 0);")
        self.gridLayout_3 = QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.liq_on = QPushButton(self.groupBox)
        self.liq_on.setObjectName(u"liq_on")
        self.liq_on.setEnabled(True)
        sizePolicy3.setHeightForWidth(self.liq_on.sizePolicy().hasHeightForWidth())
        self.liq_on.setSizePolicy(sizePolicy3)
        self.liq_on.setFont(font)
        self.liq_on.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.liq_on.setStyleSheet(u"background-color: rgb(85, 0, 0);")
        self.liq_on.setCheckable(True)

        self.gridLayout_3.addWidget(self.liq_on, 0, 1, 1, 1)

        self.hyd_on = QPushButton(self.groupBox)
        self.hyd_on.setObjectName(u"hyd_on")
        self.hyd_on.setEnabled(True)
        sizePolicy3.setHeightForWidth(self.hyd_on.sizePolicy().hasHeightForWidth())
        self.hyd_on.setSizePolicy(sizePolicy3)
        self.hyd_on.setFont(font)
        self.hyd_on.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.hyd_on.setStyleSheet(u"background-color: rgb(85, 0, 0);")
        self.hyd_on.setCheckable(True)

        self.gridLayout_3.addWidget(self.hyd_on, 1, 1, 1, 1)

        self.label_11 = QLabel(self.groupBox)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setEnabled(True)
        self.label_11.setFont(font)
        self.label_11.setFocusPolicy(Qt.FocusPolicy.ClickFocus)

        self.gridLayout_3.addWidget(self.label_11, 3, 0, 1, 1)

        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setEnabled(True)
        self.label_8.setFont(font)
        self.label_8.setFocusPolicy(Qt.FocusPolicy.ClickFocus)

        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)

        self.smt_on = QPushButton(self.groupBox)
        self.smt_on.setObjectName(u"smt_on")
        self.smt_on.setEnabled(True)
        sizePolicy3.setHeightForWidth(self.smt_on.sizePolicy().hasHeightForWidth())
        self.smt_on.setSizePolicy(sizePolicy3)
        self.smt_on.setFont(font)
        self.smt_on.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.smt_on.setStyleSheet(u"background-color: rgb(85, 0, 0);")
        self.smt_on.setCheckable(True)

        self.gridLayout_3.addWidget(self.smt_on, 3, 1, 1, 1)

        self.label_10 = QLabel(self.groupBox)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setEnabled(True)
        self.label_10.setFont(font)
        self.label_10.setFocusPolicy(Qt.FocusPolicy.ClickFocus)

        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)

        self.label_9 = QLabel(self.groupBox)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setEnabled(True)
        self.label_9.setFont(font)
        self.label_9.setFocusPolicy(Qt.FocusPolicy.ClickFocus)

        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)

        self.ele_on = QPushButton(self.groupBox)
        self.ele_on.setObjectName(u"ele_on")
        self.ele_on.setEnabled(True)
        sizePolicy3.setHeightForWidth(self.ele_on.sizePolicy().hasHeightForWidth())
        self.ele_on.setSizePolicy(sizePolicy3)
        self.ele_on.setFont(font)
        self.ele_on.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.ele_on.setStyleSheet(u"background-color: rgb(85, 0, 0);")
        self.ele_on.setCheckable(True)

        self.gridLayout_3.addWidget(self.ele_on, 2, 1, 1, 1)

        self.gridLayout_3.setRowStretch(0, 1)
        self.gridLayout_3.setRowStretch(1, 1)
        self.gridLayout_3.setRowStretch(2, 1)
        self.gridLayout_3.setRowStretch(3, 1)
        self.gridLayout_3.setColumnStretch(0, 8)
        self.gridLayout_3.setColumnStretch(1, 1)

        self.verticalLayout_3.addWidget(self.groupBox)

        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 1)

        self.horizontalLayout.addWidget(self.frame_7)

        self.groupBox_6 = QGroupBox(self.frame_4)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setEnabled(True)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.groupBox_6.setStyleSheet(u"background-color: rgb(48, 0, 0);")
        self.verticalLayout_5 = QVBoxLayout(self.groupBox_6)
        self.verticalLayout_5.setSpacing(4)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.frame_8 = QFrame(self.groupBox_6)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setEnabled(True)
        self.frame_8.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.frame_8.setFrameShape(QFrame.Shape.NoFrame)
        self.frame_8.setFrameShadow(QFrame.Shadow.Raised)
        self.gridLayout_4 = QGridLayout(self.frame_8)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.label_14 = QLabel(self.frame_8)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setEnabled(True)
        self.label_14.setFont(font)
        self.label_14.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.label_14.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_4.addWidget(self.label_14, 0, 1, 1, 1)

        self.label_12 = QLabel(self.frame_8)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setEnabled(True)
        self.label_12.setFont(font)
        self.label_12.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.label_12.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)

        self.psiLabel = QLabel(self.frame_8)
        self.psiLabel.setObjectName(u"psiLabel")
        self.psiLabel.setEnabled(True)
        self.psiLabel.setFont(font)
        self.psiLabel.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.psiLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_4.addWidget(self.psiLabel, 1, 2, 1, 1)

        self.label_15 = QLabel(self.frame_8)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setEnabled(True)
        self.label_15.setFont(font)
        self.label_15.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.label_15.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_4.addWidget(self.label_15, 1, 0, 1, 1)

        self.label_16 = QLabel(self.frame_8)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setEnabled(True)
        self.label_16.setFont(font)
        self.label_16.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.label_16.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_4.addWidget(self.label_16, 0, 2, 1, 1)

        self.psiEdit = QLineEdit(self.frame_8)
        self.psiEdit.setObjectName(u"psiEdit")
        self.psiEdit.setEnabled(True)
        self.psiEdit.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.psiEdit.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.psiEdit.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly)
        self.psiEdit.setReadOnly(False)

        self.gridLayout_4.addWidget(self.psiEdit, 1, 1, 1, 1)

        self.gridLayout_4.setRowStretch(0, 1)
        self.gridLayout_4.setRowStretch(1, 1)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_4.setColumnStretch(1, 1)
        self.gridLayout_4.setColumnStretch(2, 1)

        self.verticalLayout_5.addWidget(self.frame_8)

        self.frame_6 = QFrame(self.groupBox_6)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setEnabled(True)
        self.frame_6.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.frame_6.setFrameShape(QFrame.Shape.NoFrame)
        self.frame_6.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_4 = QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.label_13 = QLabel(self.frame_6)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setEnabled(True)
        self.label_13.setFont(font)
        self.label_13.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.label_13.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_4.addWidget(self.label_13)

        self.forward = QPushButton(self.frame_6)
        self.forward.setObjectName(u"forward")
        self.forward.setEnabled(True)
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.forward.sizePolicy().hasHeightForWidth())
        self.forward.setSizePolicy(sizePolicy4)
        self.forward.setMaximumSize(QSize(40, 16777215))
        self.forward.setFont(font)
        self.forward.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.forward.setStyleSheet(u"background-color: rgb(85, 0, 0);")

        self.horizontalLayout_4.addWidget(self.forward)

        self.neutral = QPushButton(self.frame_6)
        self.neutral.setObjectName(u"neutral")
        self.neutral.setEnabled(True)
        sizePolicy4.setHeightForWidth(self.neutral.sizePolicy().hasHeightForWidth())
        self.neutral.setSizePolicy(sizePolicy4)
        self.neutral.setMaximumSize(QSize(40, 16777215))
        self.neutral.setFont(font)
        self.neutral.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.neutral.setStyleSheet(u"background-color: rgb(85, 0, 0);")

        self.horizontalLayout_4.addWidget(self.neutral)

        self.reverse = QPushButton(self.frame_6)
        self.reverse.setObjectName(u"reverse")
        self.reverse.setEnabled(True)
        sizePolicy4.setHeightForWidth(self.reverse.sizePolicy().hasHeightForWidth())
        self.reverse.setSizePolicy(sizePolicy4)
        self.reverse.setMaximumSize(QSize(40, 16777215))
        self.reverse.setFont(font)
        self.reverse.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.reverse.setStyleSheet(u"background-color: rgb(85, 0, 0);")

        self.horizontalLayout_4.addWidget(self.reverse)


        self.verticalLayout_5.addWidget(self.frame_6)

        self.verticalLayout_5.setStretch(0, 4)
        self.verticalLayout_5.setStretch(1, 2)

        self.horizontalLayout.addWidget(self.groupBox_6)

        self.frame_5 = QFrame(self.frame_4)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setEnabled(True)
        self.frame_5.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.frame_5.setFrameShape(QFrame.Shape.NoFrame)
        self.frame_5.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_4 = QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.groupBox_5 = QGroupBox(self.frame_5)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setEnabled(True)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.groupBox_5.setStyleSheet(u"background-color: rgb(48, 0, 0);")
        self.gridLayout_5 = QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.eStop = QPushButton(self.groupBox_5)
        self.eStop.setObjectName(u"eStop")
        self.eStop.setEnabled(True)
        sizePolicy3.setHeightForWidth(self.eStop.sizePolicy().hasHeightForWidth())
        self.eStop.setSizePolicy(sizePolicy3)
        self.eStop.setFont(font)
        self.eStop.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.eStop.setStyleSheet(u"background-color: rgb(85, 0, 0);")
        self.eStop.setChecked(False)
        self.eStop.setAutoDefault(False)

        self.gridLayout_5.addWidget(self.eStop, 0, 0, 1, 1)

        self.stoptimeLabel = QLabel(self.groupBox_5)
        self.stoptimeLabel.setObjectName(u"stoptimeLabel")
        self.stoptimeLabel.setEnabled(True)
        self.stoptimeLabel.setFont(font)
        self.stoptimeLabel.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.stoptimeLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.stoptimeLabel.setWordWrap(False)

        self.gridLayout_5.addWidget(self.stoptimeLabel, 0, 1, 1, 1)

        self.reset = QPushButton(self.groupBox_5)
        self.reset.setObjectName(u"reset")
        self.reset.setEnabled(True)
        sizePolicy3.setHeightForWidth(self.reset.sizePolicy().hasHeightForWidth())
        self.reset.setSizePolicy(sizePolicy3)
        self.reset.setFont(font)
        self.reset.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.reset.setStyleSheet(u"background-color: rgb(85, 0, 0);")

        self.gridLayout_5.addWidget(self.reset, 1, 0, 1, 1)

        self.stopCount = QLabel(self.groupBox_5)
        self.stopCount.setObjectName(u"stopCount")
        self.stopCount.setEnabled(True)
        self.stopCount.setFont(font)
        self.stopCount.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.stopCount.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_5.addWidget(self.stopCount, 1, 1, 1, 1)


        self.verticalLayout_4.addWidget(self.groupBox_5)

        self.groupBox_4 = QGroupBox(self.frame_5)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setEnabled(True)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.groupBox_4.setStyleSheet(u"background-color: rgb(48, 0, 0);")
        self.gridLayout_6 = QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.dataLaunch = QPushButton(self.groupBox_4)
        self.dataLaunch.setObjectName(u"dataLaunch")
        self.dataLaunch.setEnabled(True)
        sizePolicy3.setHeightForWidth(self.dataLaunch.sizePolicy().hasHeightForWidth())
        self.dataLaunch.setSizePolicy(sizePolicy3)
        self.dataLaunch.setFont(font)
        self.dataLaunch.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.dataLaunch.setStyleSheet(u"background-color: rgb(85, 0, 0);")

        self.gridLayout_6.addWidget(self.dataLaunch, 0, 0, 1, 1)

        self.serial = QPushButton(self.groupBox_4)
        self.serial.setObjectName(u"serial")
        self.serial.setEnabled(True)
        sizePolicy3.setHeightForWidth(self.serial.sizePolicy().hasHeightForWidth())
        self.serial.setSizePolicy(sizePolicy3)
        self.serial.setFont(font)
        self.serial.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.serial.setStyleSheet(u"background-color: rgb(85, 0, 0);")

        self.gridLayout_6.addWidget(self.serial, 0, 1, 1, 1)

        self.clearOutput = QPushButton(self.groupBox_4)
        self.clearOutput.setObjectName(u"clearOutput")
        self.clearOutput.setEnabled(True)
        sizePolicy3.setHeightForWidth(self.clearOutput.sizePolicy().hasHeightForWidth())
        self.clearOutput.setSizePolicy(sizePolicy3)
        self.clearOutput.setFont(font)
        self.clearOutput.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.clearOutput.setStyleSheet(u"background-color: rgb(85, 0, 0);")

        self.gridLayout_6.addWidget(self.clearOutput, 1, 0, 1, 1)

        self.pushButton_15 = QPushButton(self.groupBox_4)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setEnabled(True)
        sizePolicy3.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy3)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.pushButton_15.setStyleSheet(u"background-color: rgb(85, 0, 0);")

        self.gridLayout_6.addWidget(self.pushButton_15, 1, 1, 1, 1)

        self.clearWarning = QPushButton(self.groupBox_4)
        self.clearWarning.setObjectName(u"clearWarning")
        self.clearWarning.setEnabled(True)
        sizePolicy3.setHeightForWidth(self.clearWarning.sizePolicy().hasHeightForWidth())
        self.clearWarning.setSizePolicy(sizePolicy3)
        self.clearWarning.setFont(font)
        self.clearWarning.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.clearWarning.setStyleSheet(u"background-color: rgb(85, 0, 0);")

        self.gridLayout_6.addWidget(self.clearWarning, 2, 0, 1, 1)

        self.pushButton_17 = QPushButton(self.groupBox_4)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.pushButton_17.setEnabled(True)
        sizePolicy3.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy3)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.pushButton_17.setStyleSheet(u"background-color: rgb(85, 0, 0);")

        self.gridLayout_6.addWidget(self.pushButton_17, 2, 1, 1, 1)

        self.gridLayout_6.setRowStretch(0, 1)
        self.gridLayout_6.setRowStretch(1, 1)
        self.gridLayout_6.setRowStretch(2, 1)
        self.gridLayout_6.setColumnStretch(0, 1)
        self.gridLayout_6.setColumnStretch(1, 1)

        self.verticalLayout_4.addWidget(self.groupBox_4)

        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 1)

        self.horizontalLayout.addWidget(self.frame_5)

        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 2)

        self.verticalLayout_2.addWidget(self.frame_4)

        self.frame_3 = QFrame(self.frame_2)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setEnabled(True)
        self.frame_3.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.frame_3.setFrameShape(QFrame.Shape.NoFrame)
        self.frame_3.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.groupBox_8 = QGroupBox(self.frame_3)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setEnabled(True)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.groupBox_8.setStyleSheet(u"background-color: rgb(48, 0, 0);")
        self.gridLayout_7 = QGridLayout(self.groupBox_8)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.outputLog = QPlainTextEdit(self.groupBox_8)
        self.outputLog.setObjectName(u"outputLog")
        self.outputLog.setEnabled(True)
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        brush1 = QBrush(QColor(0, 0, 0, 255))
        brush1.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush1)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush1)
        brush2 = QBrush(QColor(255, 255, 255, 128))
        brush2.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush2)
#endif
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush2)
#endif
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush2)
#endif
        self.outputLog.setPalette(palette)
        font2 = QFont()
        font2.setPointSize(10)
        self.outputLog.setFont(font2)
        self.outputLog.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.outputLog.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.outputLog.setReadOnly(True)

        self.gridLayout_7.addWidget(self.outputLog, 0, 0, 1, 1)


        self.horizontalLayout_2.addWidget(self.groupBox_8)

        self.groupBox_7 = QGroupBox(self.frame_3)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setEnabled(True)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.groupBox_7.setStyleSheet(u"background-color: rgb(48, 0, 0);")
        self.gridLayout_8 = QGridLayout(self.groupBox_7)
        self.gridLayout_8.setObjectName(u"gridLayout_8")
        self.warningLog = QPlainTextEdit(self.groupBox_7)
        self.warningLog.setObjectName(u"warningLog")
        self.warningLog.setEnabled(True)
        palette1 = QPalette()
        brush3 = QBrush(QColor(255, 85, 0, 255))
        brush3.setStyle(Qt.BrushStyle.SolidPattern)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush3)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush1)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush3)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush3)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush1)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush1)
        brush4 = QBrush(QColor(255, 85, 0, 128))
        brush4.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush4)
#endif
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush3)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush1)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush3)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush3)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush1)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush4)
#endif
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush3)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush3)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush3)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush4)
#endif
        self.warningLog.setPalette(palette1)
        self.warningLog.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.warningLog.setStyleSheet(u"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 85, 0);")

        self.gridLayout_8.addWidget(self.warningLog, 0, 0, 1, 1)


        self.horizontalLayout_2.addWidget(self.groupBox_7)

        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)

        self.verticalLayout_2.addWidget(self.frame_3)

        self.verticalLayout_2.setStretch(0, 4)
        self.verticalLayout_2.setStretch(1, 2)

        self.verticalLayout.addWidget(self.frame_2)

        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 20)

        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 700, 17))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Runtime", None))
        self.runButton.setText(QCoreApplication.translate("MainWindow", u"Run", None))
        self.stopButton.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.runtimeLabel.setText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Connections: Online", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Motors", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Input", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Motor", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Current Set", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Motor 1", None))
        self.rpmLabel.setText(QCoreApplication.translate("MainWindow", u"0 rpm", None))
        self.rpmEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"enter rpm", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Systems On/Off", None))
        self.liq_on.setText(QCoreApplication.translate("MainWindow", u"Off", None))
        self.hyd_on.setText(QCoreApplication.translate("MainWindow", u"Off", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Something Else", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Liquid injector", None))
        self.smt_on.setText(QCoreApplication.translate("MainWindow", u"Off", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Electrical Systems", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Hydraulic Power Unit", None))
        self.ele_on.setText(QCoreApplication.translate("MainWindow", u"Off", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Clamps", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Input", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Clamp", None))
        self.psiLabel.setText(QCoreApplication.translate("MainWindow", u"0 psi", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Main", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Current psi", None))
        self.psiEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"enter psi", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Actuator", None))
        self.forward.setText(QCoreApplication.translate("MainWindow", u"F", None))
        self.neutral.setText(QCoreApplication.translate("MainWindow", u"N", None))
        self.reverse.setText(QCoreApplication.translate("MainWindow", u"R", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Emergency", None))
        self.eStop.setText(QCoreApplication.translate("MainWindow", u"Emergency Stop", None))
        self.stoptimeLabel.setText(QCoreApplication.translate("MainWindow", u"Time: 00:00:00", None))
        self.reset.setText(QCoreApplication.translate("MainWindow", u"Reset Systems", None))
        self.stopCount.setText(QCoreApplication.translate("MainWindow", u"Count: 0", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Functions", None))
        self.dataLaunch.setText(QCoreApplication.translate("MainWindow", u"Open Data Window", None))
        self.serial.setText(QCoreApplication.translate("MainWindow", u"Serial Edit", None))
        self.clearOutput.setText(QCoreApplication.translate("MainWindow", u"Clear Output Log", None))
        self.pushButton_15.setText(QCoreApplication.translate("MainWindow", u"[Assign]", None))
        self.clearWarning.setText(QCoreApplication.translate("MainWindow", u"Clear Warning Log", None))
        self.pushButton_17.setText(QCoreApplication.translate("MainWindow", u"[Assign]", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"Output Log", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"Warning Log", None))
    # retranslateUi

